[build]
  publish = "."

[[redirects]]
  from = "/success"
  to = "/thank-you.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[functions]
  directory = "netlify/functions"
